In [21]:
#Aditya Tripathi
#202318046

In [22]:
import re
import csv
import requests
import numpy as np
from bs4 import BeautifulSoup

In [5]:
#1st task
def block_multi(A, B, block_size):
    if len(A[0]) == len(B):
        result = np.zeros((A.shape[0],B.shape[1]))
        for i in range(0,A.shape[0],block_size):
            for j in range(0,B.shape[1],block_size):
                for k in range(0, A.shape[1],block_size):
                    result[i:i+block_size,j:j+block_size]+=np.dot(A[i:i+block_size,k:k+block_size],B[k:k+block_size,j:j+block_size])
        return result
    else:
       print("Matrix cannot be multiplied because of difference in sizes")
block_size = 4
A = np.array([[1, 2, 3, 4, 5, 6], [7, 8, 9, 10, 11, 12], [13, 14, 15, 16, 17, 18], [19, 20, 21, 22, 23, 24], [25, 26, 27, 28, 29, 30], [31, 32, 33, 34, 35, 36]])
B = np.array([[36, 35, 34, 33, 32, 31], [30, 29, 28, 27, 26, 25], [24, 23, 22, 21, 20, 19], [ 18, 17, 16, 15, 14, 13], [12, 11, 10, 9, 8, 7], [6, 5, 4, 3, 2, 1]])
result = block_multi(A, B, block_size)
print("A:")
for row in A:
    print(row)
print("\nB:")
for row in B:
    print(row)
print("\nResult:")
for row in result:
    print(row)

A:
[1 2 3 4 5 6]
[ 7  8  9 10 11 12]
[13 14 15 16 17 18]
[19 20 21 22 23 24]
[25 26 27 28 29 30]
[31 32 33 34 35 36]

B:
[36 35 34 33 32 31]
[30 29 28 27 26 25]
[24 23 22 21 20 19]
[18 17 16 15 14 13]
[12 11 10  9  8  7]
[6 5 4 3 2 1]

Result:
[336. 315. 294. 273. 252. 231.]
[1092. 1035.  978.  921.  864.  807.]
[1848. 1755. 1662. 1569. 1476. 1383.]
[2604. 2475. 2346. 2217. 2088. 1959.]
[3360. 3195. 3030. 2865. 2700. 2535.]
[4116. 3915. 3714. 3513. 3312. 3111.]


In [19]:
#2nd task
link = "https://open-weather13.p.rapidapi.com/city/"

cities = ["new delhi", "noida", "guwahati"]

headers = {
	"X-RapidAPI-Key": "fdb1ff3c85mshdcb6213004beb5cp1e19a5jsndc8fc8fa74a3",
	"X-RapidAPI-Host": "open-weather13.p.rapidapi.com"
}

for city in cities:
    url = link + city
    response = requests.get(url, headers=headers)
    print(city)
    print(response.json())

new delhi
{'coord': {'lon': 77.2311, 'lat': 28.6128}, 'weather': [{'id': 701, 'main': 'Mist', 'description': 'mist', 'icon': '50n'}], 'base': 'stations', 'main': {'temp': 57.27, 'feels_like': 57.4, 'temp_min': 57.18, 'temp_max': 57.36, 'pressure': 1015, 'humidity': 100}, 'visibility': 1100, 'wind': {'speed': 6.91, 'deg': 130}, 'clouds': {'all': 75}, 'dt': 1706721556, 'sys': {'type': 2, 'id': 145989, 'country': 'IN', 'sunrise': 1706665208, 'sunset': 1706704109}, 'timezone': 19800, 'id': 1261481, 'name': 'New Delhi', 'cod': 200}
noida
{'coord': {'lon': 77.33, 'lat': 28.58}, 'weather': [{'id': 500, 'main': 'Rain', 'description': 'light rain', 'icon': '10n'}], 'base': 'stations', 'main': {'temp': 57.4, 'feels_like': 56.41, 'temp_min': 57.33, 'temp_max': 57.49, 'pressure': 1015, 'humidity': 76, 'sea_level': 1015, 'grnd_level': 991}, 'visibility': 9486, 'wind': {'speed': 2.95, 'deg': 255, 'gust': 9.55}, 'rain': {'1h': 0.86}, 'clouds': {'all': 58}, 'dt': 1706721639, 'sys': {'type': 2, 'id': 1

In [20]:
#3rd task
link = "https://www.amazon.in/s?k=watch&page="

for n in range(1, 30):
    url = link + str(n)
    response = requests.get(url)
    data = []
    if (response.status_code == 200):
        soup = BeautifulSoup(response.content, "html.parser")
        for product in soup.find_all(class_ = "a-size-base-plus a-color-base a-text-normal"):
            product = product.text.strip()
            company = product.split(sep= " ", maxsplit=1)[0]
            name = product.split(sep= " ", maxsplit=1)[-1]
            data.append([n, company, name])
        with open("amazon_watch.csv", "a", encoding = "utf-8") as csvfile:
            csvwriter = csv.writer(csvfile)
            csvwriter.writerows(data)